# Generated by Django 5.1.1 on 2024-09-29 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daju_spravku', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
