# Generated by Django 5.1.1 on 2024-09-30 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daju_spravku', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(default='Разное', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='article', to='daju_spravku.category'),
        ),
    ]
