# Generated by Django 5.1.1 on 2024-10-02 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daju_spravku', '0005_alter_comment_options_remove_comment_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
    ]
